CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    external_user_id VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(320),
    username VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_users_last_login_at ON users (last_login_at);
